name: run-all-tests
on:
  pull_request:
    jobs:
      all:
        runs-on: ubuntu-latests
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
          - run: npm install
          - run: npm test
